--  _   _                  _                 _     _____              __ _       
-- | | | |                | |               | |   /  __ \            / _(_)      
-- | |_| |_   _ _ __  _ __| | __ _ _ __   __| |   | /  \/ ___  _ __ | |_ _  __ _ 
-- |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |   | |    / _ \| '_ \|  _| |/ _` |
-- | | | | |_| | |_) | |  | | (_| | | | | (_| |   | \__/\ (_) | | | | | | | (_| |
-- \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|    \____/\___/|_| |_|_| |_|\__, |
--         __/ | |                                                          __/ |
--        |___/|_|                                                         |___/ 
--
-- Github link: https://github.com/swrneko
--

-- -------- #
-- KEYBINDS #
-- -------- #

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"
local terminal = "kitty"
local fileManager = "nemo"
local browser = "zen-browser"
local prcsDispatcher = terminal .. " -e btop"
local menu = "noctalia msg panel-toggle launcher"

-- -------------------- #
-- ENVIRONMENT VARIABLES #
-- -------------------- #
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("QT_SCALE_FACTORS", "1.3")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("QT_FONT_DPI", "81")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GTK_SCALE", "1")
hl.env("GDK_DPI_SCALE", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_SCALE_FACTOR_ROUNDING_POLICY", "RoundPreferFloor")
hl.env("GTK_USE_PORTAL", "1")

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- -------- #
-- DISPLAYS #
-- -------- #
-- Universal monitor setup


-- Don't forget to edit this
-- Because setup is for external monitor for notebook with disabled internal one
hl.monitor({
    output = "eDP-1",
    disabled = true,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144",
    position = "0x0",
    scale = "1",
})

-- --------- #
-- AUTOSTART #
-- --------- #
-- Core components

-- System services

-- User Applications (Uncomment what you need)
-- exec-once = Telegram -startintray 
-- exec-once = [workspace 10 silent] steam -silent 
-- exec-once = [workspace 10 silent] discord --start-minimized
-- exec-once = [workspace 1 silent] zen-browser 
-- exec-once = udiskie -s -m flat --menu-update-workaround
-- exec-once = /opt/v2rayn-bin/v2rayN
-- exec-once = wayvnc 0.0.0.0 5900 # Warning: Opens VNC to local network

-- --- NVIDIA FIXES (Uncomment if you use an Nvidia GPU) ---
-- env = LIBVA_DRIVER_NAME,nvidia
-- env = XDG_SESSION_TYPE,wayland
-- env = GBM_BACKEND,nvidia-drm
-- env = __GLX_VENDOR_LIBRARY_NAME,nvidia

-- ------- #
-- GENERAL #
-- ------- #

-- dynamic-cursors plugin
if hl.plugin.dynamic_cursors then
    hl.config {
        plugin = {
            dynamic_cursors = {
                enabled = true,
                mode = "stretch",
                threshold = 1,

                stretch = {
                    limit = 3000,
                    activation = "quadratic",
                    window = 100,
                },

                shake = {
                    enabled = true,
                    threshold = 6.0,
                    base = 4.0,
                    speed = 4.0,
                    influence = 0.0,
                    limit = 0.0,
                    timeout = 2000,
                    effects = false,
                    ipc = false,
                },

                hyprcursor = {
                    nearest = false,
                    enabled = true,
                    resolution = -1,
                    fallback = "left_ptr",
                },
            },
        },
    }
end

-- hl.layer_rule({
--    match = { namespace = "match:namespace waybar" },
--    -- TODO: manual review — unmapped layer rule: "blur on"
--    ignore_alpha = 1,
-- }) 

hl.layer_rule({
    match = { namespace = "match:namespace logout_dialog" },
    animation = "fade",
})

hl.layer_rule({
    match = { namespace = "match:namespace selection" },
    animation = "fade",
})

hl.layer_rule({
    match = { namespace = "match:namespace noctalia-background-.*$" },
    -- TODO: manual review — unmapped layer rule: "blur on"
    ignore_alpha = 0.35,
})

hl.curve("wind", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1 } } })
hl.curve("winIn", { type = "bezier", points = { { 0.1, 1 }, { 0.1, 1.05 } } })
hl.curve("layIn", { type = "bezier", points = { { 0.1, 1 }, { 0.1, 1.1 } } })
hl.curve("layOut", { type = "bezier", points = { { 0.3, 0 }, { 0, 1 } } })
hl.curve("winOut", { type = "bezier", points = { { 0.3, 0 }, { 0, 1 } } })
hl.curve("liner", { type = "bezier", points = { { 1, 1 }, { 1, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 6,
    bezier = "wind",
    style = "slide",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 6,
    bezier = "winIn",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 6,
    bezier = "winOut",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 6,
    bezier = "wind",
    style = "slide",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1,
    bezier = "liner",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 30,
    bezier = "liner",
    style = "loop",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "wind",
})
hl.animation({
    leaf = "specialWorkspaceIn",
    enabled = true,
    speed = 5,
    bezier = "winIn",
    style = "slidevert",
})
hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 6,
    bezier = "winOut",
    style = "slidevert",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 5,
    bezier = "layIn",
    style = "slide",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 5,
    bezier = "layOut",
    style = "slide",
})

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + U", hl.dsp.exec_cmd(prcsDispatcher))

hl.bind(mainMod .. " + M", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = 0, action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + S", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.window.pseudo())

hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + ALT + E", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 2%-"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +2%"), { repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind(mainMod .. " + Tab", hl.dsp.window.cycle_next({ prev = true }))
hl.bind("ALT + Tab", hl.dsp.window.bring_to_top())

hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp -d)\" - | wl-copy"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("mkdir -p ~/Pictures/Screenshots && grim -g \"$(slurp -d)\" - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d-%H%M%S').png | wl-copy"))

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.focus({ window = "tiled" }))
hl.bind(mainMod .. " + N", hl.dsp.focus({ window = "floating" }))

hl.bind(mainMod .. " + CONTROL + H", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CONTROL + L", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CONTROL + K", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CONTROL + J", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })

hl.bind(mainMod .. " + CONTROL + left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CONTROL + right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CONTROL + up", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CONTROL + down", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })

hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.swap({ direction = "d" }))

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.swap({ direction = "d" }))

hl.bind(mainMod .. " + ALT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.window_rule({
    match = {
        class = "Waydroid",
    },
    float = true,
    fullscreen = true,
    float = true,
})

hl.window_rule({
    match = {
        xwayland = 1,
    },
    no_blur = true,
})

hl.window_rule({
    match = {
        xwayland = 1,
        float = 1,
    },
    no_initial_focus = true,
})

hl.window_rule({
    match = {
        float = 1,
    },
    no_dim = true,
})

hl.window_rule({
    name = "dialogs-float-center",
    match = {
        title = "^(Open|Save|Choose|Select|Library|File Upload|Choose wallpaper)(.*)$",
    },
    float = true,
    center = true,
})

hl.workspace_rule({
    workspace = "1",
    default_name = "一",
})

hl.workspace_rule({
    workspace = "2",
    default_name = "二",
})

hl.workspace_rule({
    workspace = "3",
    default_name = "三",
})

hl.workspace_rule({
    workspace = "4",
    default_name = "四",
})

hl.workspace_rule({
    workspace = "5",
    default_name = "五",
})

hl.workspace_rule({
    workspace = "6",
    default_name = "六",
})

hl.workspace_rule({
    workspace = "7",
    default_name = "七",
})

hl.workspace_rule({
    workspace = "8",
    default_name = "八",
})

hl.workspace_rule({
    workspace = "9",
    default_name = "九",
})

hl.workspace_rule({
    workspace = "10",
    default_name = "十",
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
        border_size = 3,
        col = {
            active_border = "rgb(7366bd)",
            inactive_border = "rgb(4c4f69)",
        },
        layout = "dwindle",
        allow_tearing = false,
        resize_on_border = true,
        extend_border_grab_area = 15,
    },
    input = {
        kb_layout = "us, ru",
        kb_options = "grp:alt_shift_toggle",
        force_no_accel = 1,
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0.2,
    },
    dwindle = {
        -- pseudotile = yes 
        preserve_split = true,
        force_split = 2,
    },
    cursor = {
        no_warps = true,
        no_hardware_cursors = true,
    },
    xwayland = {
        enabled = true,
        force_zero_scaling = true,
        use_nearest_neighbor = true,
    },
    group = {
        auto_group = false,
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        layers_hog_keyboard_focus = true,
    },
    -- ----------- #
    -- DECORATIONS # 
    -- ----------- #
    decoration = {
        rounding = 18,
        active_opacity = 1.0,
        fullscreen_opacity = 1.0,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            popups = false,
            popups_ignorealpha = 0.15,
            ignore_opacity = true,
        },
        shadow = {
            enabled = false,
        },
        dim_inactive = true,
        dim_strength = 0.25,
        dim_around = 0.1,
    },
    -- ---------- #
    -- ANIMATIONS #
    -- ---------- #
    animations = {
        enabled = true,
    },
    -- Program launch
    -- Window mode
    -- bind = $mainMod SHIFT, T, togglesplit 
    -- System keybinds
    -- Win + Shift + S — screenshot + buffer
    -- Brightness keybinds
    -- Music & Volume keybinds (using WirePlumber)
    -- Super Tab Feature
    -- Make screenshot (Saves to ~/Pictures/Screenshots)
    -- Move focus with mainMod + HJKL
    -- Move focus with mainMod + Arrow Keys
    -- Resize with mainMod + Ctrl + HJKL
    -- Resize with mainMod + Ctrl + Arrow Keys
    -- Move window with mainMod + Shift + HJKL
    -- Move window with mainMod + Shift + Arrow Keys
    -- Workspaces
    -- ------------ #
    -- WINDOW RULES #
    -- ------------ #
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland &")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-gtk &")
    hl.exec_cmd("xrdb ~/.Xresources")
    hl.exec_cmd("xembedsniproxy")
    hl.exec_cmd("otd-daemon")
    hl.exec_cmd("cpupower frequency-set -g performance")
end)

